### ISSUE TITLE
zsh: command not found: genhtml

### ISSUE THREAD

**Issue by rrifafauzikomara** [felangel/codemagic_bloc_unit_tests#1]
Hi @felangel 

I interested using `Codemagic` with combine with flutter bloc and yes I already implemented in my project that already released. But I confused about how to add `code coverage`. I already follow [this](https://blog.codemagic.io/flutter-unit-testing-bloc-with-codemagic/) to add unit test bloc + Codemagic. But when I running the test using below:

```
flutter test --coverage && genhtml coverage/lcov.info --output=coverage
```

This is the result:
```
00:09 +4: All tests passed!                                                                                                                                                                         
zsh: command not found: genhtml
```

The query of `&& genhtml coverage/lcov.info --output=coverage` didn't run it. And also when I run this:

```
open coverage/index.html
```

This is the result:
```
The file /Users/rrifafauzikomara/Downloads/codemagic_bloc_unit_tests/coverage/index.html does not exist.
```

This is not open the `Coverage report` like this [tutorial](https://blog.codemagic.io/flutter-unit-testing-bloc-with-codemagic/).

And when I clone this project, and running the script on the terminal, still not work

**Comment by felangel** [comment]
Hi @rrifafauzikomara 👋 
You need to have `lcov` install in the docker container or on the machine that's running the tests.
If you're on `macOS` you can `brew install lcov`.

You can also use [lcov_cop](https://github.com/marketplace/actions/lcov-cop) to enforce code coverage via github actions 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
